# Generated by Django 4.1.6 on 2023-03-19 10:32

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerbTense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tense', models.CharField(choices=[(1, 'Present'), (2, 'Past'), (3, 'Future')], max_length=50)),
                ('state', django_fsm.FSMIntegerField(default=1)),
                ('verb', models.CharField(max_length=50)),
            ],
        ),
    ]
